[project]
name = "iveh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "requests>=2.32.3",
    "rerun-sdk>=0.23.3",
    "tqdm>=4.67.1",
]
